version: '3.7'

services:
  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: qdrant
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__API_KEY: ""  # Explicitly disable API key
    expose:
      - "6333"  # HTTP API
      - "6334"  # GRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always

volumes:
  qdrant_storage:
